# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changepasswordDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_changePasswordDialog(object):
    def __init__(self):
        self.changePasswordDialog = QtWidgets.QDialog()
        self.setupUi()
        self.changePasswordDialog.show()

    def setupUi(self):
        self.changePasswordDialog.setObjectName("changePasswordDialog")
        self.changePasswordDialog.resize(565, 286)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changePasswordDialog.sizePolicy().hasHeightForWidth())
        self.changePasswordDialog.setSizePolicy(sizePolicy)
        self.changePasswordDialog.setFocusPolicy(QtCore.Qt.NoFocus)
        self.gridLayout = QtWidgets.QGridLayout(self.changePasswordDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.changePasswordDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.mainFrame = QtWidgets.QFrame(self.changePasswordDialog)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lowerFrame = QtWidgets.QFrame(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowerFrame.sizePolicy().hasHeightForWidth())
        self.lowerFrame.setSizePolicy(sizePolicy)
        self.lowerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lowerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lowerFrame.setObjectName("lowerFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.lowerFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.oldPassword = QtWidgets.QLabel(self.lowerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oldPassword.sizePolicy().hasHeightForWidth())
        self.oldPassword.setSizePolicy(sizePolicy)
        self.oldPassword.setObjectName("oldPassword")
        self.horizontalLayout_3.addWidget(self.oldPassword)
        self.oldPasswordLine = QtWidgets.QLineEdit(self.lowerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oldPasswordLine.sizePolicy().hasHeightForWidth())
        self.oldPasswordLine.setSizePolicy(sizePolicy)
        self.oldPasswordLine.setTabletTracking(False)
        self.oldPasswordLine.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.oldPasswordLine.setText("")
        self.oldPasswordLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.oldPasswordLine.setClearButtonEnabled(False)
        self.oldPasswordLine.setObjectName("oldPasswordLine")
        self.horizontalLayout_3.addWidget(self.oldPasswordLine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.password = QtWidgets.QLabel(self.lowerFrame)
        self.password.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password.sizePolicy().hasHeightForWidth())
        self.password.setSizePolicy(sizePolicy)
        self.password.setObjectName("password")
        self.horizontalLayout.addWidget(self.password)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.lowerFrame)
        self.passwordLineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLineEdit.sizePolicy().hasHeightForWidth())
        self.passwordLineEdit.setSizePolicy(sizePolicy)
        self.passwordLineEdit.setTabletTracking(False)
        self.passwordLineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.passwordLineEdit.setText("")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setClearButtonEnabled(False)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.horizontalLayout.addWidget(self.passwordLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Repassword = QtWidgets.QLabel(self.lowerFrame)
        self.Repassword.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Repassword.sizePolicy().hasHeightForWidth())
        self.Repassword.setSizePolicy(sizePolicy)
        self.Repassword.setObjectName("Repassword")
        self.horizontalLayout_2.addWidget(self.Repassword)
        self.RepasswordLineEdit = QtWidgets.QLineEdit(self.lowerFrame)
        self.RepasswordLineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RepasswordLineEdit.sizePolicy().hasHeightForWidth())
        self.RepasswordLineEdit.setSizePolicy(sizePolicy)
        self.RepasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.RepasswordLineEdit.setObjectName("RepasswordLineEdit")
        self.horizontalLayout_2.addWidget(self.RepasswordLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.lowerFrame)
        self.errorFrame = QtWidgets.QFrame(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errorFrame.sizePolicy().hasHeightForWidth())
        self.errorFrame.setSizePolicy(sizePolicy)
        self.errorFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.errorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.errorFrame.setObjectName("errorFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.errorFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Errortext = QtWidgets.QLabel(self.errorFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Errortext.sizePolicy().hasHeightForWidth())
        self.Errortext.setSizePolicy(sizePolicy)
        self.Errortext.setObjectName("Errortext")
        self.verticalLayout_4.addWidget(self.Errortext)
        self.verticalLayout.addWidget(self.errorFrame)
        self.gridLayout.addWidget(self.mainFrame, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.changePasswordDialog)
        self.changePasswordDialog.setTabOrder(self.passwordLineEdit, self.RepasswordLineEdit)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.changePasswordDialog.setWindowTitle(_translate("changePasswordDialog", "Please enter your password"))
        self.oldPassword.setText(_translate("changePasswordDialog", "<html><head/><body><p><span style=\" font-size:9pt;\">Old password</span></p></body></html>"))
        self.password.setText(_translate("changePasswordDialog", "<html><head/><body><p><span style=\" font-size:9pt;\">New password</span></p></body></html>"))
        self.Repassword.setText(_translate("changePasswordDialog", "<html><head/><body><p><span style=\" font-size:9pt;\">Re-enter </span></p><p><span style=\" font-size:9pt;\">new Password</span></p></body></html>"))
        self.Errortext.setText(_translate("changePasswordDialog", "<html><head/><body><p><span style=\" color:#ff0000;\">Password must contain atleast 8 character with atleast 1 digit and 1 capital letter.</span></p></body></html>"))
