# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsDialog2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_settingDialog(object):
    def setupUi(self, settingDialog):
        settingDialog.setObjectName("settingDialog")
        settingDialog.resize(870, 461)
        self.gridLayout = QtWidgets.QGridLayout(settingDialog)
        self.gridLayout.setContentsMargins(5, 2, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(settingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 30))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(757, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.closeMe = QtWidgets.QPushButton(self.widget)
        self.closeMe.setMinimumSize(QtCore.QSize(0, 20))
        self.closeMe.setDefault(True)
        self.closeMe.setObjectName("closeMe")
        self.horizontalLayout.addWidget(self.closeMe)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)
        self.settings = QtWidgets.QTabWidget(settingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings.sizePolicy().hasHeightForWidth())
        self.settings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.settings.setFont(font)
        self.settings.setObjectName("settings")
        self.tabAppearance = QtWidgets.QWidget()
        self.tabAppearance.setObjectName("tabAppearance")
        self.themeChoice = QtWidgets.QComboBox(self.tabAppearance)
        self.themeChoice.setGeometry(QtCore.QRect(10, 70, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.themeChoice.setFont(font)
        self.themeChoice.setObjectName("themeChoice")
        self.themeChoice.addItem("")
        self.themeChoice.addItem("")
        self.themeLabel = QtWidgets.QLabel(self.tabAppearance)
        self.themeLabel.setGeometry(QtCore.QRect(10, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.themeLabel.setFont(font)
        self.themeLabel.setObjectName("themeLabel")
        self.fontSizeLabel = QtWidgets.QLabel(self.tabAppearance)
        self.fontSizeLabel.setGeometry(QtCore.QRect(10, 160, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.fontSizeLabel.setFont(font)
        self.fontSizeLabel.setObjectName("fontSizeLabel")
        self.fontChoice = QtWidgets.QFontComboBox(self.tabAppearance)
        self.fontChoice.setGeometry(QtCore.QRect(140, 230, 226, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.fontChoice.setFont(font)
        self.fontChoice.setObjectName("fontChoice")
        self.fontFamilyLabel = QtWidgets.QLabel(self.tabAppearance)
        self.fontFamilyLabel.setGeometry(QtCore.QRect(10, 230, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.fontFamilyLabel.setFont(font)
        self.fontFamilyLabel.setObjectName("fontFamilyLabel")
        self.fontSizeValue = QtWidgets.QSpinBox(self.tabAppearance)
        self.fontSizeValue.setGeometry(QtCore.QRect(140, 160, 191, 31))
        self.fontSizeValue.setMinimum(1)
        self.fontSizeValue.setMaximum(255)
        self.fontSizeValue.setObjectName("fontSizeValue")
        self.settings.addTab(self.tabAppearance, "")
        self.tabPlugins = QtWidgets.QWidget()
        self.tabPlugins.setObjectName("tabPlugins")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabPlugins)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hardExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hardExt.setFont(font)
        self.hardExt.setObjectName("hardExt")
        self.verticalLayout.addWidget(self.hardExt)
        self.footnotesExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.footnotesExt.setFont(font)
        self.footnotesExt.setObjectName("footnotesExt")
        self.verticalLayout.addWidget(self.footnotesExt)
        self.defListsExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.defListsExt.setFont(font)
        self.defListsExt.setObjectName("defListsExt")
        self.verticalLayout.addWidget(self.defListsExt)
        self.mdExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mdExt.setFont(font)
        self.mdExt.setObjectName("mdExt")
        self.verticalLayout.addWidget(self.mdExt)
        self.supExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.supExt.setFont(font)
        self.supExt.setObjectName("supExt")
        self.verticalLayout.addWidget(self.supExt)
        self.subExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subExt.setFont(font)
        self.subExt.setObjectName("subExt")
        self.verticalLayout.addWidget(self.subExt)
        self.linkExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.linkExt.setFont(font)
        self.linkExt.setObjectName("linkExt")
        self.verticalLayout.addWidget(self.linkExt)
        self.symbolsExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.symbolsExt.setFont(font)
        self.symbolsExt.setObjectName("symbolsExt")
        self.verticalLayout.addWidget(self.symbolsExt)
        self.strikeExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.strikeExt.setFont(font)
        self.strikeExt.setObjectName("strikeExt")
        self.verticalLayout.addWidget(self.strikeExt)
        self.settings.addTab(self.tabPlugins, "")
        self.tabEncryption = QtWidgets.QWidget()
        self.tabEncryption.setObjectName("tabEncryption")
        self.enterPwdLabel = QtWidgets.QLabel(self.tabEncryption)
        self.enterPwdLabel.setGeometry(QtCore.QRect(10, 20, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.enterPwdLabel.setFont(font)
        self.enterPwdLabel.setObjectName("enterPwdLabel")
        self.encryptAllChoice = QtWidgets.QCheckBox(self.tabEncryption)
        self.encryptAllChoice.setEnabled(False)
        self.encryptAllChoice.setGeometry(QtCore.QRect(10, 140, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.encryptAllChoice.setFont(font)
        self.encryptAllChoice.setChecked(True)
        self.encryptAllChoice.setObjectName("encryptAllChoice")
        self.frame_2 = QtWidgets.QFrame(self.tabEncryption)
        self.frame_2.setGeometry(QtCore.QRect(10, 60, 451, 57))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setContentsMargins(-1, -1, 10, 9)
        self.horizontalLayout_6.setSpacing(57)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.enterPwd = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.enterPwd.setFont(font)
        self.enterPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.enterPwd.setObjectName("enterPwd")
        self.horizontalLayout_6.addWidget(self.enterPwd)
        self.okPushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.okPushButton_2.setObjectName("okPushButton_2")
        self.horizontalLayout_6.addWidget(self.okPushButton_2)
        self.Errortext = QtWidgets.QLabel(self.tabEncryption)
        self.Errortext.setGeometry(QtCore.QRect(490, 65, 281, 31))
        self.Errortext.setObjectName("Errortext")
        self.settings.addTab(self.tabEncryption, "")
        self.userTab = QtWidgets.QWidget()
        self.userTab.setObjectName("userTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.userTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 6, -1, 6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.oldPassword = QtWidgets.QLabel(self.userTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oldPassword.sizePolicy().hasHeightForWidth())
        self.oldPassword.setSizePolicy(sizePolicy)
        self.oldPassword.setObjectName("oldPassword")
        self.horizontalLayout_4.addWidget(self.oldPassword)
        self.oldPasswordLineEdit = QtWidgets.QLineEdit(self.userTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oldPasswordLineEdit.sizePolicy().hasHeightForWidth())
        self.oldPasswordLineEdit.setSizePolicy(sizePolicy)
        self.oldPasswordLineEdit.setTabletTracking(False)
        self.oldPasswordLineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.oldPasswordLineEdit.setText("")
        self.oldPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.oldPasswordLineEdit.setClearButtonEnabled(False)
        self.oldPasswordLineEdit.setObjectName("oldPasswordLineEdit")
        self.horizontalLayout_4.addWidget(self.oldPasswordLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 6, -1, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.password_2 = QtWidgets.QLabel(self.userTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_2.sizePolicy().hasHeightForWidth())
        self.password_2.setSizePolicy(sizePolicy)
        self.password_2.setObjectName("password_2")
        self.horizontalLayout_2.addWidget(self.password_2)
        self.passwordLineEdit_2 = QtWidgets.QLineEdit(self.userTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLineEdit_2.sizePolicy().hasHeightForWidth())
        self.passwordLineEdit_2.setSizePolicy(sizePolicy)
        self.passwordLineEdit_2.setTabletTracking(False)
        self.passwordLineEdit_2.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.passwordLineEdit_2.setText("")
        self.passwordLineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit_2.setClearButtonEnabled(False)
        self.passwordLineEdit_2.setObjectName("passwordLineEdit_2")
        self.horizontalLayout_2.addWidget(self.passwordLineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 6, -1, 6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Repassword = QtWidgets.QLabel(self.userTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Repassword.sizePolicy().hasHeightForWidth())
        self.Repassword.setSizePolicy(sizePolicy)
        self.Repassword.setObjectName("Repassword")
        self.horizontalLayout_3.addWidget(self.Repassword)
        self.RepasswordLineEdit = QtWidgets.QLineEdit(self.userTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RepasswordLineEdit.sizePolicy().hasHeightForWidth())
        self.RepasswordLineEdit.setSizePolicy(sizePolicy)
        self.RepasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.RepasswordLineEdit.setObjectName("RepasswordLineEdit")
        self.horizontalLayout_3.addWidget(self.RepasswordLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.frame = QtWidgets.QFrame(self.userTab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setContentsMargins(200, 0, 200, 0)
        self.horizontalLayout_5.setSpacing(94)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.okPushButton = QtWidgets.QPushButton(self.frame)
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout_5.addWidget(self.okPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(self.frame)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout_5.addWidget(self.cancelPushButton)
        self.verticalLayout_2.addWidget(self.frame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.settings.addTab(self.userTab, "")
        self.gridLayout.addWidget(self.settings, 0, 0, 1, 1)

        self.retranslateUi(settingDialog)
        self.settings.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(settingDialog)

    def retranslateUi(self, settingDialog):
        _translate = QtCore.QCoreApplication.translate
        settingDialog.setWindowTitle(_translate("settingDialog", "Settings"))
        self.closeMe.setText(_translate("settingDialog", "OK"))
        self.themeChoice.setItemText(0, _translate("settingDialog", "Light Theme"))
        self.themeChoice.setItemText(1, _translate("settingDialog", "Dark Theme"))
        self.themeLabel.setText(_translate("settingDialog", "Theme:"))
        self.fontSizeLabel.setText(_translate("settingDialog", "Font Size:"))
        self.fontFamilyLabel.setText(_translate("settingDialog", "Font Family:"))
        self.settings.setTabText(self.settings.indexOf(self.tabAppearance), _translate("settingDialog", "Appearance"))
        self.hardExt.setText(_translate("settingDialog", "Enable hard breaks"))
        self.footnotesExt.setText(_translate("settingDialog", "Enable Footnotes"))
        self.defListsExt.setText(_translate("settingDialog", "Enable Definition Lists"))
        self.mdExt.setText(_translate("settingDialog", "Enable Markdown in HTML"))
        self.supExt.setText(_translate("settingDialog", "Enable Superscript"))
        self.subExt.setText(_translate("settingDialog", "Enable Subscript"))
        self.linkExt.setText(_translate("settingDialog", "Enable Auto Detect Links"))
        self.symbolsExt.setText(_translate("settingDialog", "Enable Smart Symbols"))
        self.strikeExt.setText(_translate("settingDialog", "Enable Strike"))
        self.settings.setTabText(self.settings.indexOf(self.tabPlugins), _translate("settingDialog", "Plugins"))
        self.enterPwdLabel.setText(_translate("settingDialog", "Enter Password to access encyption settings:"))
        self.encryptAllChoice.setText(_translate("settingDialog", "Encrypt all notes"))
        self.enterPwd.setPlaceholderText(_translate("settingDialog", "Enter Password"))
        self.okPushButton_2.setText(_translate("settingDialog", "Ok"))
        self.settings.setTabText(self.settings.indexOf(self.tabEncryption), _translate("settingDialog", "Encryption"))
        self.oldPassword.setText(_translate("settingDialog", "Old Password"))
        self.password_2.setText(_translate("settingDialog", "New Password"))
        self.Repassword.setText(_translate("settingDialog", "Re-enter Password"))
        self.okPushButton.setText(_translate("settingDialog", "Ok"))
        self.cancelPushButton.setText(_translate("settingDialog", "Cancel"))
        self.settings.setTabText(self.settings.indexOf(self.userTab), _translate("settingDialog", "User"))
