# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsDialog2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_settingDialog(object):
    def setupUi(self, settingDialog):
        settingDialog.setObjectName("settingDialog")
        settingDialog.resize(870, 461)
        self.gridLayout = QGridLayout(settingDialog)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(5, 2, 5, 5)
        self.settings = QTabWidget(settingDialog)
        self.settings.setObjectName(u"settings")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings.sizePolicy().hasHeightForWidth())
        self.settings.setSizePolicy(sizePolicy)
        font = QFont()
        font.setFamily(u"Calibri")
        font.setPointSize(14)
        self.settings.setFont(font)
        self.settings.setObjectName("settings")
        self.tabAppearance = QtWidgets.QWidget()
        self.tabAppearance.setObjectName("tabAppearance")
        self.themeChoice = QtWidgets.QComboBox(self.tabAppearance)
        self.themeChoice.setGeometry(QtCore.QRect(10, 70, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.themeChoice.setFont(font)
        self.themeChoice.setObjectName("themeChoice")
        self.themeChoice.addItem("")
        self.themeChoice.addItem("")
        self.themeLabel = QtWidgets.QLabel(self.tabAppearance)
        self.themeLabel.setGeometry(QtCore.QRect(10, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.themeLabel.setFont(font)
        self.themeLabel.setObjectName("themeLabel")
        self.fontSizeLabel = QtWidgets.QLabel(self.tabAppearance)
        self.fontSizeLabel.setGeometry(QtCore.QRect(10, 160, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.fontSizeLabel.setFont(font)
        self.fontSizeLabel.setObjectName("fontSizeLabel")
        self.fontChoice = QtWidgets.QFontComboBox(self.tabAppearance)
        self.fontChoice.setGeometry(QtCore.QRect(140, 230, 226, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.fontChoice.setFont(font)
        self.fontChoice.setObjectName("fontChoice")
        self.fontFamilyLabel = QtWidgets.QLabel(self.tabAppearance)
        self.fontFamilyLabel.setGeometry(QtCore.QRect(10, 230, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.fontFamilyLabel.setFont(font)
        self.fontFamilyLabel.setObjectName("fontFamilyLabel")
        self.fontSizeValue = QtWidgets.QSpinBox(self.tabAppearance)
        self.fontSizeValue.setGeometry(QtCore.QRect(140, 160, 191, 31))
        self.fontSizeValue.setMinimum(1)
        self.fontSizeValue.setMaximum(255)
        self.fontSizeValue.setObjectName("fontSizeValue")
        self.settings.addTab(self.tabAppearance, "")
        self.tabPlugins = QtWidgets.QWidget()
        self.tabPlugins.setObjectName("tabPlugins")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabPlugins)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hardExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hardExt.setFont(font)
        self.hardExt.setObjectName("hardExt")
        self.verticalLayout.addWidget(self.hardExt)
        self.footnotesExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.footnotesExt.setFont(font)
        self.footnotesExt.setObjectName("footnotesExt")
        self.verticalLayout.addWidget(self.footnotesExt)
        self.defListsExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.defListsExt.setFont(font)
        self.defListsExt.setObjectName("defListsExt")
        self.verticalLayout.addWidget(self.defListsExt)
        self.mdExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mdExt.setFont(font)
        self.mdExt.setObjectName("mdExt")
        self.verticalLayout.addWidget(self.mdExt)
        self.supExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.supExt.setFont(font)
        self.supExt.setObjectName("supExt")
        self.verticalLayout.addWidget(self.supExt)
        self.subExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subExt.setFont(font)
        self.subExt.setObjectName("subExt")
        self.verticalLayout.addWidget(self.subExt)
        self.linkExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.linkExt.setFont(font)
        self.linkExt.setObjectName("linkExt")
        self.verticalLayout.addWidget(self.linkExt)
        self.symbolsExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.symbolsExt.setFont(font)
        self.symbolsExt.setObjectName("symbolsExt")
        self.verticalLayout.addWidget(self.symbolsExt)
        self.strikeExt = QtWidgets.QCheckBox(self.tabPlugins)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStrikeOut(False)
        self.strikeExt.setFont(font)
        self.strikeExt.setObjectName("strikeExt")
        self.verticalLayout.addWidget(self.strikeExt)
        self.settings.addTab(self.tabPlugins, "")
        self.tabEncryption = QtWidgets.QWidget()
        self.tabEncryption.setObjectName("tabEncryption")
        self.enterPwd = QtWidgets.QLineEdit(self.tabEncryption)
        self.enterPwd.setGeometry(QtCore.QRect(10, 70, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.enterPwd.setFont(font)
        self.enterPwd.setObjectName("enterPwd")
        self.enterPwdLabel = QtWidgets.QLabel(self.tabEncryption)
        self.enterPwdLabel.setGeometry(QtCore.QRect(10, 20, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.enterPwdLabel.setFont(font)
        self.enterPwdLabel.setObjectName("enterPwdLabel")
        self.encryptAllChoice = QtWidgets.QCheckBox(self.tabEncryption)
        self.encryptAllChoice.setEnabled(False)
        self.encryptAllChoice.setGeometry(QtCore.QRect(10, 140, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.encryptAllChoice.setFont(font)
        self.encryptAllChoice.setChecked(True)
        self.encryptAllChoice.setObjectName("encryptAllChoice")
        self.settings.addTab(self.tabEncryption, "")
        self.userTab = QtWidgets.QWidget()
        self.userTab.setObjectName("userTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.userTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 6, -1, 6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.oldPassword = QtWidgets.QLabel(self.userTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oldPassword.sizePolicy().hasHeightForWidth())
        self.oldPassword.setSizePolicy(sizePolicy)
        self.oldPassword.setObjectName("oldPassword")
        self.horizontalLayout_4.addWidget(self.oldPassword)
        self.oldPasswordLineEdit = QtWidgets.QLineEdit(self.userTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oldPasswordLineEdit.sizePolicy().hasHeightForWidth())
        self.oldPasswordLineEdit.setSizePolicy(sizePolicy)
        self.oldPasswordLineEdit.setTabletTracking(False)
        self.oldPasswordLineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.oldPasswordLineEdit.setText("")
        self.oldPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.oldPasswordLineEdit.setClearButtonEnabled(False)
        self.oldPasswordLineEdit.setObjectName("oldPasswordLineEdit")
        self.horizontalLayout_4.addWidget(self.oldPasswordLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 6, -1, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.password_2 = QtWidgets.QLabel(self.userTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_2.sizePolicy().hasHeightForWidth())
        self.password_2.setSizePolicy(sizePolicy)
        self.password_2.setObjectName("password_2")
        self.horizontalLayout_2.addWidget(self.password_2)
        self.passwordLineEdit_2 = QtWidgets.QLineEdit(self.userTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLineEdit_2.sizePolicy().hasHeightForWidth())
        self.passwordLineEdit_2.setSizePolicy(sizePolicy)
        self.passwordLineEdit_2.setTabletTracking(False)
        self.passwordLineEdit_2.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.passwordLineEdit_2.setText("")
        self.passwordLineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit_2.setClearButtonEnabled(False)
        self.passwordLineEdit_2.setObjectName("passwordLineEdit_2")
        self.horizontalLayout_2.addWidget(self.passwordLineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 6, -1, 6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Repassword = QtWidgets.QLabel(self.userTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Repassword.sizePolicy().hasHeightForWidth())
        self.Repassword.setSizePolicy(sizePolicy)
        self.Repassword.setObjectName("Repassword")
        self.horizontalLayout_3.addWidget(self.Repassword)
        self.RepasswordLineEdit = QtWidgets.QLineEdit(self.userTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RepasswordLineEdit.sizePolicy().hasHeightForWidth())
        self.RepasswordLineEdit.setSizePolicy(sizePolicy)
        self.RepasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.RepasswordLineEdit.setObjectName("RepasswordLineEdit")
        self.horizontalLayout_3.addWidget(self.RepasswordLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.frame = QtWidgets.QFrame(self.userTab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setContentsMargins(200, 0, 200, 0)
        self.horizontalLayout_5.setSpacing(94)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.okPushButton = QtWidgets.QPushButton(self.frame)
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout_5.addWidget(self.okPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(self.frame)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout_5.addWidget(self.cancelPushButton)
        self.verticalLayout_2.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem)
        self.settings.addTab(self.userTab, "")
        self.gridLayout.addWidget(self.settings, 0, 0, 1, 1)

        self.widget = QWidget(settingDialog)
        self.widget.setObjectName(u"widget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy1)
        self.widget.setMinimumSize(QSize(0, 30))
        self.widget.setMaximumSize(QSize(16777215, 30))
        self.horizontalLayout = QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer = QSpacerItem(757, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.closeMe = QPushButton(self.widget)
        self.closeMe.setObjectName(u"closeMe")
        self.closeMe.setMinimumSize(QSize(0, 20))

        self.horizontalLayout.addWidget(self.closeMe)


        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)


        self.retranslateUi(settingDialog)
        self.settings.setCurrentIndex(0)
        self.closeMe.setDefault(True)


        QMetaObject.connectSlotsByName(settingDialog)
    # setupUi

    def retranslateUi(self, settingDialog):
        settingDialog.setWindowTitle(QCoreApplication.translate("settingDialog", u"Settings", None))
        self.themeChoice.setItemText(0, QCoreApplication.translate("settingDialog", u"Light Theme", None))
        self.themeChoice.setItemText(1, QCoreApplication.translate("settingDialog", u"Dark Theme", None))

        self.themeLabel.setText(QCoreApplication.translate("settingDialog", u"Theme:", None))
        self.fontSizeLabel.setText(QCoreApplication.translate("settingDialog", u"Font size:", None))
        self.fontFamilyLabel.setText(QCoreApplication.translate("settingDialog", u"Font Family:", None))
        self.settings.setTabText(self.settings.indexOf(self.tabAppearance), QCoreApplication.translate("settingDialog", u"Appearance", None))
        self.hardExt.setText(QCoreApplication.translate("settingDialog", u"Enable hard breaks", None))
        self.footnotesExt.setText(QCoreApplication.translate("settingDialog", u"Enable Footnotes", None))
        self.defListsExt.setText(QCoreApplication.translate("settingDialog", u"Enable Definition Lists", None))
        self.mdExt.setText(QCoreApplication.translate("settingDialog", u"Enable Markdown in HTML", None))
        self.supExt.setText(QCoreApplication.translate("settingDialog", u"Enable Superscript", None))
        self.subExt.setText(QCoreApplication.translate("settingDialog", u"Enable Subscript", None))
        self.linkExt.setText(QCoreApplication.translate("settingDialog", u"Enable Auto Detect Links", None))
        self.symbolsExt.setText(QCoreApplication.translate("settingDialog", u"Enable Smart Symbols", None))
        self.strikeExt.setText(QCoreApplication.translate("settingDialog", u"Enable Strike", None))
        self.settings.setTabText(self.settings.indexOf(self.tabPlugins), QCoreApplication.translate("settingDialog", u"Plugins", None))
        self.enterPwd.setPlaceholderText(QCoreApplication.translate("settingDialog", u"Enter Password", None))
        self.enterPwdLabel.setText(QCoreApplication.translate("settingDialog", u"Enter Password to access encyption settings:", None))
        self.encryptAllChoice.setText(QCoreApplication.translate("settingDialog", u"Encrypt all notes", None))
        self.changePwdChoice.setText(QCoreApplication.translate("settingDialog", u"Change Password", None))
        self.settings.setTabText(self.settings.indexOf(self.tabEncryption), QCoreApplication.translate("settingDialog", u"Encryption", None))
        self.closeMe.setText(QCoreApplication.translate("settingDialog", u"OK", None))
    # retranslateUi

