
from PySide2 import QtCore, QtGui, QtWidgets


class Ui_verifyPasswordDialog(object):
    def __init__(self):
        self.verifyPasswordDialog = QtWidgets.QDialog()
        self.setupUi()
        self.verifyPasswordDialog.show()

    def setupUi(self):
        self.verifyPasswordDialog.setObjectName("verifyPasswordDialog")
        self.verifyPasswordDialog.resize(565, 286)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verifyPasswordDialog.sizePolicy().hasHeightForWidth())
        self.verifyPasswordDialog.setSizePolicy(sizePolicy)
        self.verifyPasswordDialog.setFocusPolicy(QtCore.Qt.NoFocus)
        self.gridLayout = QtWidgets.QGridLayout(self.verifyPasswordDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verifyPasswordDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.mainFrame = QtWidgets.QFrame(self.verifyPasswordDialog)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upperFrame = QtWidgets.QFrame(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.upperFrame.sizePolicy().hasHeightForWidth())
        self.upperFrame.setSizePolicy(sizePolicy)
        self.upperFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.upperFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.upperFrame.setObjectName("upperFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.upperFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.instruction = QtWidgets.QLabel(self.upperFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instruction.sizePolicy().hasHeightForWidth())
        self.instruction.setSizePolicy(sizePolicy)
        self.instruction.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.instruction.setWordWrap(False)
        self.instruction.setObjectName("instruction")
        self.gridLayout_2.addWidget(self.instruction, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.upperFrame)
        self.lowerFrame = QtWidgets.QFrame(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowerFrame.sizePolicy().hasHeightForWidth())
        self.lowerFrame.setSizePolicy(sizePolicy)
        self.lowerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lowerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lowerFrame.setObjectName("lowerFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.lowerFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.password = QtWidgets.QLabel(self.lowerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password.sizePolicy().hasHeightForWidth())
        self.password.setSizePolicy(sizePolicy)
        self.password.setObjectName("password")
        self.horizontalLayout.addWidget(self.password)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.lowerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLineEdit.sizePolicy().hasHeightForWidth())
        self.passwordLineEdit.setSizePolicy(sizePolicy)
        self.passwordLineEdit.setTabletTracking(False)
        self.passwordLineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.passwordLineEdit.setText("")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setClearButtonEnabled(False)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.horizontalLayout.addWidget(self.passwordLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.lowerFrame)
        self.errorFrame = QtWidgets.QFrame(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errorFrame.sizePolicy().hasHeightForWidth())
        self.errorFrame.setSizePolicy(sizePolicy)
        self.errorFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.errorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.errorFrame.setObjectName("errorFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.errorFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Errortext = QtWidgets.QLabel(self.errorFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Errortext.sizePolicy().hasHeightForWidth())
        self.Errortext.setSizePolicy(sizePolicy)
        self.Errortext.setObjectName("Errortext")
        self.verticalLayout_4.addWidget(self.Errortext)
        self.verticalLayout.addWidget(self.errorFrame)
        self.gridLayout.addWidget(self.mainFrame, 0, 0, 1, 1)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.verifyPasswordDialog)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.verifyPasswordDialog.setWindowTitle(_translate("verifyPasswordDialog", "Please enter your password"))
        self.instruction.setText(_translate("verifyPasswordDialog", "<html><head/><body><p>Please enter <span style=\" font-weight:600;\">password </span>to enter decrypt the note.</p><p>Keep in mind that you have to <span style=\" font-weight:600;\">remember </span>your password to read the content of the note</p><p>and that you can <span style=\" font-weight:600;\">only</span> do that <span style=\" font-weight:600;\">in Groot</span>.</p></body></html>"))
        self.password.setText(_translate("verifyPasswordDialog", "<html><head/><body><p><span style=\" font-size:9pt;\">Password</span></p></body></html>"))
        self.Errortext.setText(_translate("verifyPasswordDialog", "<html><head/><body><p><br/></p></body></html>"))

